Script started on Thu 02 May 2019 07:33:32 PM PDT
]0;tungfang@klaatu:~/hw4[?1034h[tungfang@klaatu hw4]$ gdb gasp
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux 8.0.1-36.el7
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gasp...done.
(gdb) set args -i "basketba[K[KBall [K" file1.txt
(gdb) break main
Breakpoint 1 at 0x400876: file gasp.c, line 29.
(gdb) breakfope[K[K[K[K fopen
Breakpoint 2 at 0x400750
(gdb) run
Starting program: /homes/tungfang/hw4/gasp -i "basketBall" file1.txt
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.3.x86_64

Breakpoint 1, main (argc=4, argv=0x7fffffffe068) at gasp.c:29
29	    ignoreCase = 0; 
(gdb) print argv[2]
$1 = 0x7fffffffe33a "basketBall"
(gdb) c
Continuing.

Breakpoint 2, 0x00007ffff7a7cad0 in fopen@@GLIBC_2.2.5 () from /lib64/libc.so.6
(gdb) bt[K[Kbt
#0  0x00007ffff7a7cad0 in fopen@@GLIBC_2.2.5 () from /lib64/libc.so.6
#1  0x0000000000400a23 in searchMatches (fileName=0x7fffffffe345 "file1.txt", 
    str=0x7fffffffe33a "basketball") at gasp.c:65
#2  0x00000000004009df in main (argc=4, argv=0x7fffffffe068) at gasp.c:55
(gdb) list 65
60	}
61	
62	// Given a argument count, argument value and string to find the match 
63	// among files
64	void searchMatches(char *fileName, char *str) {
65	    FILE* file = fopen(fileName, "r"); // pointer to current file
66	
67	    if (file == NULL) {
68	        fprintf(stderr, "Cannot open %s\n", fileName);
69	    }
(gdb) up
#1  0x0000000000400a23 in searchMatches (fileName=0x7fffffffe345 "file1.txt", 
    str=0x7fffffffe33a "basketball") at gasp.c:65
65	    FILE* file = fopen(fileName, "r"); // pointer to current file
(gdb) print fileName
$2 = 0x7fffffffe345 "file1.txt"
(gdb) print file
$3 = (FILE *) 0x0
(gdb) c
Continuing.
file1.txt:I 1 like to play basketball
file1.txt:basketball 4 never stop
[Inferior 1 (process 22209) exited normally]
(gdb) quit
]0;tungfang@klaatu:~/hw4[tungfang@klaatu hw4]$ exit
exit

Script done on Thu 02 May 2019 07:35:48 PM PDT
